In [4]:
import torch
import numpy as np

In [5]:
data=[
    [1,2],
    [3,4]
]
x_data=torch.tensor(data)
print(x_data)

np_array=np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [10]:
shape=(2,3)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.3644, 0.4705, 0.7519],
        [0.7370, 0.8767, 0.0188]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
tensor=torch.rand(2,3)

torch.Size([2, 3])

In [12]:
tensor.shape

torch.Size([2, 3])

In [13]:
tensor.dtype

torch.float32

In [14]:
tensor.device

device(type='cpu')

In [19]:
if torch.cuda.is_available():
    tensor=tensor.to("cpu")
    print("yes")
else:
    print("NO")

NO


In [20]:
torch.cuda.is_available()

False

In [25]:
tensor=torch.ones(2,3)*2

In [26]:
y3=torch.matmul(tensor,tensor.T)
print(y3)

tensor([[12., 12.],
        [12., 12.]])


실습 1

In [35]:
data1=[[1,2],[3,4]]
data2=[[5,6],[7,8]]
d1=torch.tensor(data1)
d2=torch.tensor(data2)
d_mul=d1@ d2
print(d_mul)
print(d_mul.sum().item())
d_ele_mul=torch.mul(d1,d2)
print(d_ele_mul)

tensor([[19, 22],
        [43, 50]])
134
tensor([[ 5, 12],
        [21, 32]])


In [5]:
x=torch.ones(2,2,requires_grad=True)
y1=x+2
print(y1)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [7]:
x=torch.tensor(2.0,requires_grad=True)
y=3*x**2+4*x+1
y.backward()
print(x.grad)

tensor(16.)


In [8]:
x=torch.tensor(1.0,requires_grad=True)
z=torch.tensor(2.0,requires_grad=True)
y=x**3+z**2
y.backward()
print(x.grad)
print(z.grad)

tensor(3.)
tensor(4.)
